### ISSUE TITLE
alsa.pc missing

### ISSUE THREAD

**Issue by FauthD** [jojo61/vdr-plugin-softhdodroid#1]
Hi jojo61,
just trying to build on Armbian focal (40€ TV box Tanix TX3). There it complains about alsa.pc is not found.
Solution was to install:
`sudo apt install libasound2-dev`

Perhaps that sould go into the readme.

PS: Now I have to search for the next issue:
`amports/amstream.h:55:10: fatal error: amports/vformat.h: No such file or directory
55 | #include "amports/vformat.h"`

Thanks for this plugin !!!
Dieter (also in vdr-portal)

**Comment by FauthD** [comment]
Hi, 
regarding the  the "error: amports/vformat.h":
I had to add "-I." to the CFLAGS, then it finds it.

Which compiler do you use?
I have 
`cc -v`

`Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04)`

Perhaps it is configured differently that yours? Have seen such issues often with different customers (before I retired :-).
Regards, Dieter

PC: Linker now complains about missing mail stuff. Will look into at next days.

**Comment by jojo61** [comment]
Hi,

I use ubuntu as development environment. Maybe that is a bit different than Armbian. My Compiler is:

cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1 20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 

I wonder what you mean with missing mail. There is no mail whatsoever in the Plugin :-)

PS: I will update the readme about the missing libasound-dev
I would like to know your progress with the Tanix Box.  Looks good for a vdr.

**Comment by FauthD** [comment]
Hi,
sorry, my fault: not mail, I wanted to write MALI. I think there is a lib that should go into the requirements list. Will keep you posted.

Yes, this box would be a nice VDR. 
My Nvidia 630 is EOL for drivers, so I thought to look into something new. I have an N2+ running as home server with good success, but nobody could deliver another one these days. Than I found this box.
Meanwhile I boot from an SSD via USB3. In worst case it gets a pi-hole or a Kodi-box with CoreElec.

Many regards, Dieter

**Comment by FauthD** [comment]
Hi, 
on my x86 Ubuntu 20.04 machine I also need the ' -I.' (gcc 9.3.0).
I assume you do not build inside the vdr source dir, do you? At least your readme talks about the independent build.

BTW: Had to install vdr-dev additionally to vdr. 
In very old days the vdr-dev was the "NG" kind of branch from Klaus. Back at 2.2 -> 2.4 from my recall.
Today it seems to contain the PKGCFG stuff. Very good.

I now forked, so I can send you pull requests.

Many regards, Dieter

**Comment by FauthD** [comment]
Hi again,
libmali is missing on Armbian. That's the reason for the ld error.
I now try to create an image with startup from Armbian and rootfs from Ubuntu.
My USB -> Sata Adapter is sick today (had this before), so its time to create a new stick anyway.

**Comment by FauthD** [comment]
Mixed image with Armbian boot and Ubuntu rootfs seems to work.

**Comment by FauthD** [comment]
ok, with Ubuntu it builds just fine.
The Armbian build is something I might look into later - after  I have seen vdr running :-) hardly can wait.
BTW. I am running kernel 5.15 right now. Was in my boot directory from my Armbian tests.

Booting these TV boxes requires a few tricks and settings for u-boot. Some guys from the Armbian team did a great job to figure that out.

BTW2: In case someone had booted CoreElec, other OS like LibreElec, Armbian etc will not boot anymore.
The official fix is to reflash the nand with original image - which is not available in many cases.
A much simpler and faster method is to delete the variable "bootfromsd" in u-boot. Then use the "toothpick method with the new OS.

**Comment by FauthD** [comment]
Seams my kernel v5.15 is still not ok. Will try the 4.9 later. Could be next week.

At start this is the output:
`open CODEC_CNTL_DEVICE failed.
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
open /dev/ion failed.failed to initialize EGL display
No EGL Config found
No config found
no Context created`

In syslog I see this:
`Feb 18 16:21:34 tx3u vdr: [35978] [softhddev]ERROR::cOglOutputFb: Framebuffer is not complete!
Feb 18 16:21:34 tx3u vdr: [35978] [softhddev]ERROR: 660 Framebuffer is not complete!
Feb 18 16:21:34 tx3u vdr: [35964] [softhddev] cannot allocate pixmap of 624px x 403px, clipped to 0px x 0px!
Feb 18 16:21:34 tx3u vdr: [35978] [softhddev]ERROR: 660 Framebuffer is not complete!
Feb 18 16:21:44 tx3u vdr: [35978] [softhddev]ERROR: 660 Framebuffer is not complete!
Feb 18 16:21:44 tx3u vdr: [35964] [softhddev] cannot allocate pixmap of 624px x 403px, clipped to 0px x 0px!
Feb 18 16:21:44 tx3u vdr: [35978] [softhddev]ERROR: 660 Framebuffer is not complete!
Feb 18 16:21:54 tx3u vdr: [35978] [softhddev]ERROR: 660 Framebuffer is not complete!
Feb 18 16:21:54 tx3u vdr: [35964] [softhddev] cannot allocate pixmap of 624px x 403px, clipped to 0px x 0px!
Feb 18 16:21:54 tx3u vdr: [35978] [softhddev]ERROR: 660 Framebuffer is not complete!`

**Comment by jojo61** [comment]
It seems that you are missing mali. Also it will only run with the hardkernel 4.9 kernel as there as changes that did not make it upstream. Beta has provided a very good kernel based on 4.9  with some patches for screen capture:
https://github.com/beta68/linux

**Comment by FauthD** [comment]
Hi Jojo, 
yes, I also look into this kernel. At least to duplicate your success.
Problem is probably the device tree. Might need to backport a DT from 5.16 to 4.9 -can be quite tendentious.
Have compiled that kernel with an "at least very close" DTB. Will try to run it soon.
Forked from Beta68 now.

Will keep you posted.

**Comment by jojo61** [comment]
Seems fixed now
