### ISSUE TITLE
Lots of warnings

### ISSUE THREAD

**Issue by FauthD** [jojo61/vdr-plugin-softhdodroid#2]
Hi, 
I get a few screens with warnings. Too much for my taste.
Typical signed/unsigned issues. Sometimes these bite you when you not expect it.

At least the last few look fishy to my old eyes:
`                    case 6:
                        if (AudioChannelsInHw[7]) {
                            AudioChannelMatrix[u][chan] = 7;
                            break;
                        }`
(idents are lost here)
Or is that on purpose?  To parse the same data in different case statements?

Many regards, Dieter

**Comment by jojo61** [comment]
The Audio Part is very old and also not from me. I did not bother to correct it as long as it works.

Patches for silencing compile warnings are welcome :-) 

mfg
Jojo
