### ISSUE TITLE
vdr-dev should be added to readme

### ISSUE THREAD

**Issue by FauthD** [jojo61/vdr-plugin-softhdodroid#3]
Hi, 
apt install vdr-dev was required here on both Ubuntu and Armbian

PS: The libasound2-dev was already install in the hardkernel ubuntu image.
But it does not hurt to add to the list.

P": I can send a pull request for the Makefile (-I.). Also does not hurt. Many toolchains need that (at least I have seen that requirement often in my job).

**Comment by jojo61** [comment]
Yes, please send a pull request for the Makefile. I will update the README for vdr-dev
