### ISSUE TITLE
Why need to run vdr as root?

### ISSUE THREAD

**Issue by FauthD** [jojo61/vdr-plugin-softhdodroid#4]
Hi Jojo,
is this  because we need to access certain devices?
Then a udev rule would help.
I'd be glad to create one.

Many rards, Dieter
PS: Perhaps this wa my issues at friday. I did not run vdr as root. So there is hope...

**Comment by jojo61** [comment]
Yes we need to access certain amstream devices. But I do not now exactly why we need root.  The devices are all 666. Maybe it is audiodsp.  Anyway I did not bother running root.
